In [6]:
movies = ["Inception", "Interstellar", "Avatar", "Hangover", "Joker"]

# first & last
print(movies[0], movies[-1])

# add & remove
movies.append("Matrix")
movies.pop(1)
print(movies)

# sort
movies.sort()
print(movies)

# length & check
print(len(movies))
print("Avatar" in movies)

Inception Joker
['Inception', 'Avatar', 'Hangover', 'Joker', 'Matrix']
['Avatar', 'Hangover', 'Inception', 'Joker', 'Matrix']
5
True


In [7]:
cities = ("Chennai", "Salem", "Mumbai", "Bangalore", "Delhi")

print(cities[1], cities[3])

# cities[0] = "Madurai"  # ❌ Error: tuple is immutable

# unpacking
a, b, c, d, e = cities
print(a, b, c, d, e)

# convert
city_list = list(cities)
city_list.append("Madurai")
cities = tuple(city_list)
print(cities)

Salem Bangalore
Chennai Salem Mumbai Bangalore Delhi
('Chennai', 'Salem', 'Mumbai', 'Bangalore', 'Delhi', 'Madurai')


In [8]:
student = {
    "name": "Vignesh",
    "age": 20,
    "grade": "A",
    "city": "Salem"
}

print(student.keys())
print(student.values())
print(student.items())

student["grade"] = "A+"
student["email"] = "vignesh@email.com"

del student["city"]
print(student)

dict_keys(['name', 'age', 'grade', 'city'])
dict_values(['Vignesh', 20, 'A', 'Salem'])
dict_items([('name', 'Vignesh'), ('age', 20), ('grade', 'A'), ('city', 'Salem')])
{'name': 'Vignesh', 'age': 20, 'grade': 'A+', 'email': 'vignesh@email.com'}


In [ ]:
weekday = {"Math", "Physics", "Python"}
weekend = {"Python", "AI", "ML"}

print(weekday | weekend)   # union
print(weekday & weekend)   # intersection
print(weekday - weekend)   # difference

weekday.add("English")
weekend.remove("ML")

print("AI" in weekday or "AI" in weekend)

{'AI', 'Math', 'ML', 'Python', 'Physics'}
{'Python'}
{'Physics', 'Math'}
True


In [9]:
def greet(name):
    print(f"Hello, {name}! Welcome to Day 2.")

def add_numbers(a, b):
    return a + b

def find_max(a, b, c):
    return max(a, b, c)

def is_even(n):
    return n % 2 == 0

greet("Vignesh")
print(add_numbers(5, 10))
print(find_max(3, 7, 5))
print(is_even(4))

Hello, Vignesh! Welcome to Day 2.
15
7
True


In [10]:
def introduce(name, language="Python"):
    print(f"{name} is learning {language}")

introduce("Vignesh")
introduce("Vignesh", "SQL")

def calculate_discount(price, discount=10):
    return price - (price * discount / 100)

print(calculate_discount(1000))

Vignesh is learning Python
Vignesh is learning SQL
900.0


In [ ]:
num = int(input("Enter number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

score = int(input("Enter score: "))
if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
elif score >= 60:
    print("D")
else:
    print("F")

year = int(input("Enter year: "))
if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
    print("Leap Year")
else:
    print("Not Leap Year")

Enter number: 53
Positive
Enter score: 50
F
Enter year: 2007
Not Leap Year


In [ ]:
# 1 to 20
for i in range(1, 21):
    print(i)

# even numbers
for i in range(2, 51, 2):
    print(i)

# fruits with index
fruits = ["apple", "banana", "cherry"]
for i in range(len(fruits)):
    print(i, fruits[i])

# sum 1 to 100
total = 0
for i in range(1, 101):
    total += i
print(total)

# vowels count
text = "hello world"
count = 0
for ch in text:
    if ch in "aeiou":
        count += 1
print(count)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
0 apple
1 banana
2 cherry
5050
3


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

print(np.zeros(10))
print(np.ones(10))

print(np.arange(1, 21))
print(np.linspace(0, 1, 7))

print(np.random.randint(1, 101, 8))

[10 20 30 40 50]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[82 45 89 33 74 34 12 90]


In [ ]:
print(np.zeros((3,3)))
print(np.eye(3))
print(np.full((4,4), 7))
print(np.random.rand(3,4))

print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0.03545465 0.77030354 0.02203576 0.33373096]
 [0.38082026 0.16345377 0.54537308 0.1032769 ]
 [0.40458709 0.03439138 0.44192977 0.91427381]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.random.randint(1,10,(4,5))

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

2
(4, 5)
20
int64
8
160


In [ ]:
a = np.array([1,2,3])
print(a.dtype)

b = np.array([1.1,2.2])
print(b.dtype)

c = a.astype(float)
print(a, c)

d = np.array([1,2.5,3])
print(d.dtype)

e = np.array(["a","b","c"], dtype=str)
print(e.dtype)

int64
float64
[1 2 3] [1. 2. 3.]
float64
<U1


In [ ]:
arr = np.zeros(10)
arr[5] = 99
print(arr)

print(np.arange(0,51,5))

mat = np.eye(5)
print(np.diag(mat))

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[ 0.  0.  0.  0.  0. 99.  0.  0.  0.  0.]
[ 0  5 10 15 20 25 30 35 40 45 50]
[1. 1. 1. 1. 1.]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
arr = np.arange(1,16)

print(arr[:5])
print(arr[-3:])
print(arr[::2])

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mat[1,2])
print(mat[1,:])
print(mat[:,2])

[1 2 3 4 5]
[13 14 15]
[ 1  3  5  7  9 11 13 15]
6
[4 5 6]
[3 6 9]


In [ ]:
arr = np.arange(1,16)

print(arr[:5])
print(arr[-3:])
print(arr[::2])

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mat[1,2])
print(mat[1,:])
print(mat[:,2])

[1 2 3 4 5]
[13 14 15]
[ 1  3  5  7  9 11 13 15]
6
[4 5 6]
[3 6 9]
